### ISSUE TITLE
Github Track courses to be completed

### ISSUE THREAD

**Issue by mrance21** [mrance21/Treehouse#2]
## TODO

*Courses left to complete the Treehouse Github track*

* [ ] Working by yourself
* [ ] Working on a team
* [ ] Create a Web Presence on Github

🎉 🙆‍♂ 💯
